// http://projecteuler.net/problem=2
//
// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:
//         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.
//
// Answer: 4613732

#include <iostream>

int main(int argc, char* argv[]) {
    long long a = 0;
    long long b = 1;
    long long sum = 0;
    long long FIBO_LIMIT = 4000000;
    for (long long c = a + b; c < FIBO_LIMIT; a = b, b = c, c = a + b) {
        std::cout << c << "\n";
        if ((c & 1) == 0)
            sum += c;
    }
    std::cout << sum << "\n";
}
